### PR TITLE
feat: #360 Organization Page/details

### PR DESCRIPTION
**Pull request by nolliia**
Screenshot 2024-08-08 at 11 13 46
Screenshot 2024-08-08 at 11 14 08
Screenshot 2024-08-08 at 11 14 16
Screenshot 2024-08-08 at 11 14 31

please vote on which one you like more, couldn't decide :)

## Summary by Sourcery

Add an 'Organizations' page and update dataset components to use 'organization' instead of 'catalogue'. Update navigation to include a link to the new 'Organizations' page.

New Features:
- Introduce an 'Organizations' page that lists all organizations with their details and links to their datasets.
- Add a new 'Organizations' link to the header and navigation menu.

Enhancements:
- Replace 'catalogue' references with 'organization' in dataset-related components and services for better clarity and consistency.

Tests:
- Update tests to reflect the change from 'catalogue' to 'organization' in dataset properties.

### CODE REVIEW

**Comment by EmiPali** [comment]
The second option for me.

**Comment by nolliia** [comment]
@EmiPali what about this :

image

**Comment by EmiPali** [comment]
@nolliia Well now I am in between.
 I think the info-colour (blue-ish) one eases a bit the duality of colours of the page purple and black, but that colour with the black naming of the organisation don't go well together.

**Comment by brunopacheco1** [comment]
@EmiPali the colour may change, there is another story to review that.

**Review by brunopacheco1 — APPROVED** [review]

**Pull request merged**
