### PR TITLE
Improve datasets details view

### PR DESCRIPTION
**Pull request by brunopacheco1**
Large screen:
image

Smaller screen:
image

### CODE REVIEW

**Comment by admy7** [comment]
Some texts exceed their container, such as the text for language. Will the text be shortened as some point (e.g. for language, display only  "Croatian" instead of "https//.../HRV") ?

**Comment by admy7** [comment]
What does the text below the title represent? 

It looks like a description + some extra metadata describing the content of the data

**Comment by brunopacheco1** [comment]
> What does the text below the title represent?
> 
> It looks like a description + some extra metadata describing the content of the data

It is the description of the dataset, but the content is coming from the harvester.

**Comment by brunopacheco1** [comment]
> Some texts exceed their container, such as the text for language. Will the text be shortened as some point (e.g. for language, display only "Croatian" instead of "https//.../HRV") ?

Indeed, but this has to be fixed in CKAN, using ckanext-scheming.

**Review by hcvdwerf — APPROVED** [review]

**Review by admy7 — APPROVED** [review]

**Pull request merged**
