### PR TITLE
feat: Add to Basket button on dataset details page

### PR DESCRIPTION
**Pull request by inderps**
Screenshot 2024-03-06 at 10 25 57
Screenshot 2024-03-06 at 10 25 52

### CODE REVIEW

**Comment by inderps** [comment]
Another idea

Screenshot 2024-03-06 at 10 50 22
Screenshot 2024-03-06 at 10 50 26

**Comment by nolliia** [comment]
don't you think it will look better when it is in the right of the title and not all the way down as the user will have to scroll down to add it, take a look at the picture for my example
image

**Comment by inderps** [comment]
> don't you think it will look better when it is in the right of the title and not all the way down as the user will have to scroll down to add it, take a look at the picture for my example image

The only issue i could see when the title is very large

**Comment by inderps** [comment]
@nolliia @brunopacheco1 

Screenshot 2024-03-06 at 11 55 28

**Comment by nolliia** [comment]
I like it a lot

**Comment by nolliia** [comment]
> @nolliia @brunopacheco1
> 
> Screenshot 2024-03-06 at 11 55 28


I like it a lot

**Review by brunopacheco1 — APPROVED** [review]

**Pull request merged**
