### PR TITLE
fix: use correct colors

### PR DESCRIPTION
**Pull request by inderps**
Screenshot 2024-03-07 at 16 22 36
Screenshot 2024-03-07 at 16 22 40

### CODE REVIEW

**Comment by nolliia** [comment]
is it just me or the icons aren't aligned? I like the the approach for the colors btw

**Comment by inderps** [comment]
Also i think our nav buttons are too rounded. This is inconsistent with other buttons across our app. So i made it consistent everywhere

Before

Screenshot 2024-03-07 at 16 30 04

After
Screenshot 2024-03-07 at 16 32 06

**Comment by nolliia** [comment]
> Also i think our nav buttons are too rounded. This is inconsistent with other buttons across our app. So i made it consistent everywhere
> 
> Before
> 
> Screenshot 2024-03-07 at 16 30 04
> After Screenshot 2024-03-07 at 16 32 06

I like the rounded ones better, but that's just me

**Comment by inderps** [comment]
@nolliia But then It's consistent. Beauty is in consistency

**Pull request merged**
