### PR TITLE
feat: consistent colouring

### PR DESCRIPTION
**Pull request by inderps**
I've noticed that 3 new colors have been added into our GDI app which are not present in our design guidelines. While these changes may enhance visual appeal but i believe adhering to color palette is quite important for brand consistency, visual harmony and professionalism.

If we don't actively look out for this, we could end up with a lot of colours everywhere

I'm open to discuss and debate about this

### CODE REVIEW

**Comment by admy7** [comment]
Can you provide screenshots of the changes please? Thank you 🙏

**Comment by nolliia** [comment]
for me GDI Website/GitHub Issues should be in blue for two reasons 
1- it is a link and usually links are bleu
2- purple looks the same as the footer and the disclaimer that it just makes it not as highlighted.

other then that I agree with the making the text black and not grey

**Comment by brunopacheco1** [comment]
I also agree the purpleish colour should not be used for links. Specially with the sidebar of dataset details, there will be eventually links there.

**Review by brunopacheco1 — APPROVED** [review]
I will approve the PR to not block it, feel free to revisit this link colour in another moment.

**Comment by inderps** [comment]
@nolliia @brunopacheco1 Alright I will change the link color back to blue on About us Page

Regarding changing it also on sidebar, there i would like to debate (but lets do that in separate PR)

**Comment by inderps** [comment]
@admy7 Screenshots

Screenshot 2024-02-26 at 09 20 33
Screenshot 2024-02-26 at 09 20 40

**Review by admy7 — APPROVED** [review]

**Pull request merged**
